### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by CesarDenis** [denisristic/excel-service-provider#1]
Hi, 
I did the installation as instructed.

But when I generate the spreadsheet is giving the following error:

```
Class 'PHPExcel\Spreadsheet' not found in /silex/vendor/denisristic/excel-service-provider/src/denisristic/ExcelServiceProvider/Generator/
```

Can you help me?

**Comment by denisristic** [comment]
@CesarDenis  sorry for late response, I've made a bug fix. Please try again (just run composer update). If you have any problems be free to contact me

**Comment by CesarDenis** [comment]
Hey, @denisristic I did update and now the error is on line 28:

```
PHP Fatal error:  Class 'PHPExcel\IOFactory' not found in /silex/vendor/denisristic/excel-service-provider/src/denisristic/ExcelServiceProvider/Generator/Excel.php on line 28
```

**Comment by CesarDenis** [comment]
up

**Comment by denisristic** [comment]
Can you try now?

**Comment by CesarDenis** [comment]
@denisristic now work. Tks
